### ISSUE TITLE
调用insertMessage报错

### ISSUE THREAD

**Issue by li8607** [wildfirechat/wfc_flutter_plugins#101]
<img width="566" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/19184680/97cb00ca-533c-4191-b916-2eae5a81f2d6">

**Comment by li8607** [comment]
<img width="930" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/19184680/de0b804c-b664-4505-bf05-ad5c516f7ce7">

**Comment by li8607** [comment]
<img width="1410" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/19184680/11538049-1eaf-49ad-a15e-8cd6cc0704a1">

**Comment by li8607** [comment]
返回的是messageId int类型的，用map接就失败了

**Comment by li8607** [comment]
<img width="1382" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/19184680/ffc408bb-1eef-49f2-8779-9d0719e4096b">

**Comment by li8607** [comment]
android好像是对的

**Comment by heavyrain2012** [comment]
已经解决，请更新验证

**Comment by li8607** [comment]
<img width="637" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/19184680/e4c7e536-ea7a-4e44-8a4e-0f5c134032c1">

**Comment by li8607** [comment]
还是不行

**Comment by li8607** [comment]
<img width="1016" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/19184680/e87697cf-ac68-4156-8fa1-db2e471f6828">

**Comment by heavyrain2012** [comment]
不好意思，我们没有好好测试，现在改好了，这次应该没有问题了，请您更新检查一下

**Comment by li8607** [comment]
已检查，确认修复成功，关闭这个问题了。
