### ISSUE TITLE
会话列表lastMessage的问题

### ISSUE THREAD

**Issue by 657447158** [wildfirechat/wfc_flutter_plugins#103]
服务端修改了message.roaming = 0后，会话列表的lastMessage就拿不到值了。。
message.roaming = 1的情况下lastMessage正常。
<img width="1592" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/25770737/d580a794-d49a-41cc-a0c1-6f3ca6b0bb4a">

**Comment by heavyrain2012** [comment]
如果roaming为1，首次登录会同步最近的消息。如果为0，那么不会同步消息。如果不同步，那么本地的会话就没有最后一条消息

**Comment by 657447158** [comment]
首先有个问题，我把APP卸载了重装，不应该有本地会话才对把？现在的情况是我卸载重装或者在本机登录别的账号后，会拿到会话列表，但是最后一条消息没有，所以这是个问题。

**Comment by heavyrain2012** [comment]
IM服务有个漫游会话列表功能，专业版IM服务可以把这个功能也关掉，这样就不会有空的会话列表了，请检查IM服务配置 message.disable_roaming_conversation_list 。如果是社区版IM服务，可以在客户端做一下判断，如果最后一条消息是空，可以不现实这个会话

**Comment by 657447158** [comment]
<img width="1290" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/25770737/ec840693-b68c-443e-8394-bcd8b82dd5b5">
刚检查了 这个配置是false，专业版

**Comment by heavyrain2012** [comment]
改成true就会禁止掉会话漫游，就不会有空的会话列表了
