### ISSUE TITLE
删除会话列表会，再去获取历史记录依然有聊天记录。

### ISSUE THREAD

**Issue by 657447158** [wildfirechat/wfc_flutter_plugins#104]
<img width="1218" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/25770737/672f9aa0-fe9a-4af8-afe3-b27ed638b36a">
删除会话列表，clearMessage传true。然后再去获取该用户的历史记录，依然能拿到所有的历史记录。

**Comment by heavyrain2012** [comment]
问题出现在android还是iOS上？“再去获取该用户的历史记录”是那个接口？

**Comment by 657447158** [comment]
ios和Android都是这个情况，删除会话后，我再通过Imclient.getRemoteMessages这个接口去获取，还能拿到聊天记录。删除会话不会删除远端聊天记录吗？

**Comment by heavyrain2012** [comment]
对的，这个接口是删除本地的消息，不会删除服务器端的消息

**Comment by heavyrain2012** [comment]
检查一下这个方法 clearRemoteConversationMessage
