### ISSUE TITLE
文本消息重新编辑

### ISSUE THREAD

**Issue by SeongBrave** [wildfirechat/wfc_flutter_plugins#106]
如果消息重新编辑是调用 
`   Imclient.updateRemoteMessageContent(
      chatMsg.msg!.messageUid!,
      updateMsg,
      true,
      true,
      () {},
      (e) {},
    );` 然后只有一个删除的回调

**Comment by heavyrain2012** [comment]
确认是android sdk的问题，已经解决，请更新最新代码验证
