### ISSUE TITLE
调用获取我的文件列表报错

### ISSUE THREAD

**Issue by NeptuneCoder** [wildfirechat/wfc_flutter_plugins#107]
W/System.err( 9181): java.lang.reflect.InvocationTargetException
W/System.err( 9181): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9181): 	at cn.wildfirechat.imclient.ImclientPlugin.onMethodCall(ImclientPlugin.java:224)
W/System.err( 9181): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
W/System.err( 9181): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err( 9181): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/System.err( 9181): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err( 9181): 	at android.os.Handler.handleCallback(Handler.java:971)
W/System.err( 9181): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err( 9181): 	at android.os.Looper.loopOnce(Looper.java:206)
W/System.err( 9181): 	at android.os.Looper.loop(Looper.java:296)
W/System.err( 9181): 	at android.app.ActivityThread.main(ActivityThread.java:9194)
W/System.err( 9181): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9181): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
W/System.err( 9181): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018)
W/System.err( 9181): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
W/System.err( 9181): 	at cn.wildfirechat.imclient.ImclientPlugin.getConversationFiles(ImclientPlugin.java:1893)
W/System.err( 9181): 	... 14 more
W/OnBackInvokedCallback( 9181): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback( 9181): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
I/flutter ( 9181): {"provider": "fileListViewModelProvider",
I/flutter ( 9181):   "newValue": "AsyncData<FileListResponse>(value: Instance of 'FileListResponse')"}
V/InputMethodManager( 9181): dispatchInputEvent

**Comment by heavyrain2012** [comment]
问题已经修复，请更新最新代码验证
