### ISSUE TITLE
语音通话和视频通话，iOS 端在锁屏的情况下，无法发送声音和接收声音

### ISSUE THREAD

**Issue by moQingTing** [wildfirechat/wfc_flutter_plugins#112]

**Comment by heavyrain2012** [comment]
在发起通话后在对方接听之前进入到后台或者锁屏，对方接听时应用无法在后台启动音频功能的，这是iOS平台的限制，目前还没有找到如何是webrtc重启音频的办法。所以目前限制是不能在后台接听和被接听。当通话接听后再进入后台或者锁屏无影响
