### ISSUE TITLE
消息发送状态没有及时更新

### ISSUE THREAD

**Issue by SeongBrave** [wildfirechat/wfc_flutter_plugins#114]
我发送了消息，对方已经接收，但是状态没有及时更新成接收成功，还是MessageStatus.Message_Status_Sending

**Comment by heavyrain2012** [comment]
使用demo对比测试过吗

**Comment by SeongBrave** [comment]
这块逻辑和demo 是一样的，你们可以简单跑下试试

**Comment by heavyrain2012** [comment]
刚优化了一下，请更新最新测试看看

**Comment by heavyrain2012** [comment]
现在是发送时会返回一个message对象，后续状态变更会修改这个message对象。如果是其他方式加载的消息，则不会变化，需要监听状态然后更新
