### ISSUE TITLE
已崩溃：mars::stn::lonklink EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000115e0fdb6

### ISSUE THREAD

**Issue by li8607** [wildfirechat/wfc_flutter_plugins#117]
<img width="1274" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/19184680/51d5c4d5-2366-46a1-b0ca-7efdd2f19eb6">

麻烦帮忙看一下吧

**Comment by heavyrain2012** [comment]
这是第一次看到这个错误，以前没有见过。请问这个错误出现的频率高吗

**Comment by li8607** [comment]
不常见，就出现了一次，没有其他信息了，先关闭后续再看看
