### ISSUE TITLE
进行视频通话报错

### ISSUE THREAD

**Issue by moQingTing** [wildfirechat/wfc_flutter_plugins#118]
<img width="1151" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/18046454/81751345-d6ba-42d7-b9a3-bd2fe6dac709">

最新代码master分支
flutter 版本：
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.2, on macOS 14.3.1 23D60 darwin-x64, locale zh-Hans-CN)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.17.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/a1/fvm/versions/3.10.2. Consider adding /Users/a1/fvm/versions/3.10.2/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
a1@1deMacBook-Pro example %

**Comment by heavyrain2012** [comment]
已解决，请更新验证
