### ISSUE TITLE
视频通话未接通时，按返回键后无法取消

### ISSUE THREAD

**Issue by moQingTing** [wildfirechat/wfc_flutter_plugins#119]
播放音视频对方未接听的时候，如果返回，音视频播打就无法取消，再次拨打就会白屏，之前这里是以小窗口形式呈现。

https://github.com/wildfirechat/wfc_flutter_plugins/assets/18046454/14f6b042-1fa8-4415-ad13-e7f01440d72d

**Comment by heavyrain2012** [comment]
已解决，请更新验证

**Comment by moQingTing** [comment]
非常感谢，我刚拉取最新代码测试了demo，依然存在问题，提供了视频：

https://github.com/wildfirechat/wfc_flutter_plugins/assets/18046454/8d2a3341-bdc1-42b3-92f4-8c6400becb10

**Comment by heavyrain2012** [comment]
好像是IM没有连上，你检查一下2个端互相发消息是不是能互通的

**Comment by heavyrain2012** [comment]
测试的时候，用野火的demo，什么都不要改，用野火提供的服务，再测试，如果还是不行再录像我们看看，测试步骤是先杀掉应用，打开应用，互发消息之后，再拨打

**Comment by moQingTing** [comment]
确定是使用野火demo，没有任何改动，IM也连上，按照你说的步骤测试，能互发消息，问题依然存在，视频跟上面发的一模一样

**Comment by heavyrain2012** [comment]
录像看一下，按照这个说的测试步骤

> 测试的时候，用野火的demo，什么都不要改，用野火提供的服务，再测试，如果还是不行再录像我们看看，测试步骤是先杀掉应用，打开应用，互发消息之后，再拨打

**Comment by heavyrain2012** [comment]
工程不会有什么缓存吧，线清理一下

**Comment by moQingTing** [comment]
非常感谢你的回复，我是卸载重新安装app进行测试的，拉取你的代码后没有任何修改，按照你说的步骤测试

https://github.com/wildfirechat/wfc_flutter_plugins/assets/18046454/0114e5d4-4a6d-4d88-968e-6849243170a4

**Comment by heavyrain2012** [comment]
好的，我们这么理解错了，现在问题弄清楚了，问题已经修改，请更新验证
