### ISSUE TITLE
Demo是否可以增加CallKit相关的支持吗

### ISSUE THREAD

**Issue by SeongBrave** [wildfirechat/wfc_flutter_plugins#121]
如题，我们这边使用了咱这边的Flutter 版本SDK，但是目前iOS版本想支持与原生iOS 一样的callKit 功能，咱这边可以提供个demo支持吗？

**Comment by heavyrain2012** [comment]
已经添加，请检查最近代码提交

**Comment by SeongBrave** [comment]
@heavyrain2012 帮忙确认下咱Flutter新加的callkit功能支持配置吗？我们需要上架国内了可能需要配置成不走CallKit功能

**Comment by heavyrain2012** [comment]
在客户端，代码中有个开关用来开启callkit，如下：
```
Rtckit.enableCallkit();
```

但在推送服务，现在是有个配置是否全局使用voip push。如果voip push不使用callkit的话，应该是有问题。所以需要你们对客户端和推送服务做一下二开改动。判断哪些用户能用callkit，哪些用户不能用callkit。在客户端启动时设置是否支持callkit，在推送服务每次音视频推送时也需要判断一下是否voip推送，需要确保和客户端是否使用callkit对应上
