### ISSUE TITLE
文档提到：获取某个MessageUid之前的50条消息，如何获取某个MessageUid之后的任意条数消息？

### ISSUE THREAD

**Issue by sawwas** [wildfirechat/wfc_flutter_plugins#122]
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/cdd16710-89f4-490b-8494-033c3a7d3fd2">
文档提到：获取某个MessageUid之前的50条消息，如何获取某个MessageUid之后的任意条数消息？

**Comment by heavyrain2012** [comment]
这个是说服务器的远端消息，对应客户端的getRemoteMessages，我猜测这不是你要的接口。你们是不是想要加载本地的消息，加载本地消息接口用getMessages，如果加载某条之前的消息count用正值，如果加载某条之后的count用负值就可以了
