### ISSUE TITLE
payload里面pushData有值，但在TextMessageContent decode方法中没有对pushData处理，结果是pushData里json String 没有值，如何处理？

### ISSUE THREAD

**Issue by sawwas** [wildfirechat/wfc_flutter_plugins#123]
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/38f0414d-16f8-479b-b81c-150169c17d60">
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/a8713149-1dbe-452c-a588-756400ba5627">

**Comment by heavyrain2012** [comment]
https://github.com/wildfirechat/wfc_flutter_plugins/blob/master/imclient/android/src/main/java/cn/wildfirechat/imclient/ImclientPlugin.java  这个文件的239行，ChatManager.Instance().useRawMsg(); 这个方法调用以后，在SDK内就不会把消息转为对应的java消息，而是转化为一个包含payload的rawmessage，这样上层传下来的payload就会被透传处理，防止经过java层decode/encode丢失内容。所以理论上是不会出问题的。

你说的“结果是pushData里json String 没有值”是在那里检查的pushdata没有值的？

**Comment by sawwas** [comment]
![image](https://github.com/user-attachments/assets/d04b077b-2631-4e96-8485-d04bfbd8fbbd)
发现在本地没有ChatManager.Instance().useRawMsg()方法，是否同步git最新代码能解决这个问题？

**Comment by sawwas** [comment]
是在后端那里检查的iOS有值，安卓端pushdata没有值

**Comment by heavyrain2012** [comment]
那就是需要升级代码了，这个函数是后来加上的，你们可能用的是加上之前的代码，可以升级以后测试看看
