### ISSUE TITLE
运行编译异常

### ISSUE THREAD

**Issue by lhw88860979** [wildfirechat/wfc_flutter_plugins#127]
Task 'wrapper' not found in project ':app'.

* Try:
> Run gradle tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by heavyrain2012** [comment]
看不出什么问题，请贴出更多的编译日志

**Comment by lhw88860979** [comment]
E:\sanxinProject\flutter\saasIm\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:34: ����: �޷�����AVEngineKit
      flutterEngine.getPlugins().add(new cn.wildfirechat.rtckit.RtckitPlugin());
                                ^
  �Ҳ���cn.wildfirechat.avenginekit.AVEngineKit�����ļ�
1 ������

这个库引入是不是有问题

**Comment by heavyrain2012** [comment]
这个代码像是生成的，这块儿应该不是问题根本原因

**Comment by heavyrain2012** [comment]
no response
