### ISSUE TITLE
上传媒体文件

### ISSUE THREAD

**Issue by lhw88860979** [wildfirechat/wfc_flutter_plugins#128]
///上传媒体文件
  static void uploadMediaFile(
      String filePath,
      int mediaType,
      OperationSuccessStringCallback successCallback,
      SendMediaMessageProgressCallback progressCallback,
      OperationFailureCallback errorCallback) {
    ImclientPlatform.instance.uploadMediaFile(filePath, mediaType, successCallback, progressCallback, errorCallback);
  }
  
  这个mediaType分别是什么

**Comment by imndx** [comment]
请参考

https://github.com/wildfirechat/wfc_flutter_plugins/blob/3071611117ffba0242221aace392a2d11329c3ad/imclient/lib/message/message_content.dart#L119-L130
