### ISSUE TITLE
关于服务器端历史消息无法被删除的问题

### ISSUE THREAD

**Issue by FrancisTX** [wildfirechat/wfc_flutter_plugins#131]
最近发现我们的flutter sdk中的clearRemoteConversationMessage方法无法彻底删除聊天记录，我们的im-server是专业版。但是在这个[文档](https://docs.wildfirechat.cn/faq/general.html )里面说社区版要在设置中改`message.roaming`和`message.remote_history_message`两个参数为0。

目前主要是想问
1. 我们专业版是不是也要改这两个参数为0，目前用的是1，是不是可能因为这个导致无法删除聊天记录？
2. `message.roaming`和`message.remote_history_message` 两个参数应该是决定是否读服务器的聊天记录，都为0就是不读服务器的记录，只读本地记录。所以及时都为0的话，还是无法在服务器上面彻底删除聊天记录吗？
3. 如果以上方法无法在服务器上彻底删除聊天记录，是否有相关api可以本地和服务器同时删除聊天记录？

谢谢回答！

**Comment by imndx** [comment]
1. 不用，社区版 im-server 设置这个是因为社区版im-server 不支持删除远端消息，本地删除，然后禁止拉取远端历史消息，以达到类似的效果。
3.  `clearRemoteConversationMessage` 这个方法有回调的，回调成功了吗？或者错误码是什么？

**Comment by heavyrain2012** [comment]
> 最近发现我们的flutter sdk中的clearRemoteConversationMessage方法无法彻底删除聊天记录 

这个是什么表现，请详细描述一下

**Comment by heavyrain2012** [comment]
好的，问题先关闭，如果发现有问题再反馈
