### ISSUE TITLE
Imclient.deleteRemoteMessage()删除消息后，对方依然可以看到消息

### ISSUE THREAD

**Issue by FrancisTX** [wildfirechat/wfc_flutter_plugins#133]
Imclient.deleteRemoteMessage()应该在服务端数据库删除对应消息的吧？所以应该是这条消息双方都看不到了（群组的话就是所有群成员都看不到）。 但是我在发送方call了这个方法，只是发送方删除了此条消息，接收方仍然能看到，和Imclient.deleteMessage()的表现是一样的。

我猜测一种可能是接收方没有update这个delete的事件？咱们有相关的event可以通知所有接收方吗？因为deleteMessage删除本地消息，是有deleteMessageEvent的，但是deleteRemoteMessage并没有event通知接受方删除消息？或者有没有什么推荐的解决方案？

**Comment by heavyrain2012** [comment]
客户端删除，只能删除自己的，不能删除对方的，是单方删除。如果想要双方删除，可以调用server api的删除消息接口

**Comment by FrancisTX** [comment]
> 客户端删除，只能删除自己的，不能删除对方的，是单方删除。如果想要双方删除，可以调用server api的删除消息接口

server api指的是app-server项目中的/app-server/src/lib/sdk-1.1.9.jar!吗

具体方法的路径是/app-server/src/lib/sdk-1.1.9.jar!/cn/wildfirechat/sdk/MessageAdmin.class中的deleteMessage()方法吗？如图：
<img width="1125" alt="Screenshot 2024-12-09 at 12 59 16 AM" src="https://github.com/user-attachments/assets/e3f5d9a5-0c5d-41dc-9f8e-7bf187aae922">

**Comment by heavyrain2012** [comment]
对的

**Comment by FrancisTX** [comment]
好的 没问题 已解决 感谢！
有一点要注意是因为这边直接call的admin delete message，没有检查用户权限，应该要在服务层添加一下权限检查的逻辑。

**Comment by FrancisTX** [comment]
但是有一点好奇的是im-server端删除消息，是怎么传输deleteMessageEvent让所有用户知道有消息被删除的呢？
