### ISSUE TITLE
关于flutterSDK 的一些相关问题和bug反馈

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/wfc_flutter_plugins#15]
1 关于消息编码的问题,之前提过这个问题,但是只做了decode的处理,encode没做处理,还是会乱码
2 _convertProtoUserInfos 要判断data是不null,不然下面循环处理,会报错 (类似很多地方,都要做兼容处理)
3 缺少 onFriendRequestUpdated (好友请求更新)事件
4 图片消息的 thumbnail 要做空判断处理,不然直接decodeJpg 报错
5 语音消息,如果缺少duration 或者缺少整个content ,json 解析报错 (场景:从api发送消息的时候,如果不传相关参数)
6 视频消息:同上
7 名片消息的消息载体,缺少用户id,只有昵称 头像等,没有办法点击聊天,或者查看资料
8 更新消息和插入消息的接口 insertMessage / updateMessage content参数,需要添加await
9 createGroup 接口 notifyContent 参数设置,需要await
10  addGroupMembers / kickoffGroupMembers 接口参数名 和SDK不一致 members => groupMembers
11 modifyGroupInfo 接口 参数名 newValue=>value
...................还有其他一系列的问题
以上bug或者问题,是我们已经解决的
下面还有暂时没解决, 和解决不掉的

1.getGroupInfo接口,只有基本信息,没有 加入方式,用户数等字段

2.getGroupInfoAsync接口 直接crash...............................

**Comment by pslxx** [comment]
还有就是群组有些设置,并不起作用吗,也不知道是不是有缓存问题

以上问题,都是安卓的,在ios下,都还没测试,之前遇到过 会话聊天记录是反向排列的

**Comment by pslxx** [comment]
如果有可以,能不能有个更加快速的沟通方式,大家一起完善这个SDK,我们目前是拿这个SDK 做一个商业化的产品的..
而且在原有的基础上增加了额外的功能,中间肯定会遇到很多一些问题,希望能深入沟通完善/或者重写这个SDK

**Comment by heavyrain2012** [comment]
非常感谢给我们提出这么多宝贵的问题，您加我微信吧 wildfirechat ，咱们微信沟通

**Comment by heavyrain2012** [comment]
> 1 关于消息编码的问题,之前提过这个问题,但是只做了decode的处理,encode没做处理,还是会乱码
> 2 _convertProtoUserInfos 要判断data是不null,不然下面循环处理,会报错 (类似很多地方,都要做兼容处理)
> 3 缺少 onFriendRequestUpdated (好友请求更新)事件
> 4 图片消息的 thumbnail 要做空判断处理,不然直接decodeJpg 报错
> 5 语音消息,如果缺少duration 或者缺少整个content ,json 解析报错 (场景:从api发送消息的时候,如果不传相关参数)
> 6 视频消息:同上
> 7 名片消息的消息载体,缺少用户id,只有昵称 头像等,没有办法点击聊天,或者查看资料
> 8 更新消息和插入消息的接口 insertMessage / updateMessage content参数,需要添加await
> 9 createGroup 接口 notifyContent 参数设置,需要await
> 10 addGroupMembers / kickoffGroupMembers 接口参数名 和SDK不一致 members => groupMembers
> 11 modifyGroupInfo 接口 参数名 newValue=>value
> ...................还有其他一系列的问题
> 以上bug或者问题,是我们已经解决的
> 下面还有暂时没解决, 和解决不掉的
> 
> 1.getGroupInfo接口,只有基本信息,没有 加入方式,用户数等字段
> 
> 2.getGroupInfoAsync接口 直接crash...............................

1.getGroupInfo接口,只有基本信息,没有 加入方式,用户数等字段
现在是有用户数的，没有加入方式字段。
2.getGroupInfoAsync接口 直接crash...............................
用最新的demo，在调用getGroupInfo的地方，调用这个方法，没有发现crash，请确认

**Comment by heavyrain2012** [comment]
> 还有就是群组有些设置,并不起作用吗,也不知道是不是有缓存问题
> 
> 以上问题,都是安卓的,在ios下,都还没测试,之前遇到过 会话聊天记录是反向排列的

android端排序是有问题的，已经修正，请参考 https://github.com/wildfirechat/flutter_imclient/commit/304140dd369dab8bbdf1370e1462bc42a60749c2
