### ISSUE TITLE
2.0 版本计划

### ISSUE THREAD

**Issue by imndx** [wildfirechat/wfc_flutter_plugins#25]
1. 对接 Android 和 iOS ```client```，实现基本功能
 2. 对接 Android 和 iOS ```uikit```，实现音视频相关功能

**Comment by 657447158** [comment]
2.0版本有计划周期没？我们项目的移动端也需要使用音视频进行配合

**Comment by xiaobo1438** [comment]
请问大概什么周期 个人感觉 Flutter现在的市场还是不错的 希望贵司重视一下Flutter SDK的优化.

**Comment by heavyrain2012** [comment]
已经发布，当前master分支升级为新版本，支持即时通讯和实时音视频。之前旧版本在V1分支
