### ISSUE TITLE
小米上架隐私问题 TencentMar

### ISSUE THREAD

**Issue by qq1440214507** [wildfirechat/wfc_flutter_plugins#27]
违规收集个人信息
APP以隐私政策弹窗的形式向用户明示收集使用规则，未经用户同意，存在收集个人信息（(SDK: TencentMar) 读取WIFI的BSSID）的行为。
APP向用户明示SDK的收集使用规则，未经用户同意，SDK存在收集（(SDK: TencentMar) 读取WIFI的BSSID）的行为。
具体如下，请问android端会在启动时自动获取BSSID吗？
我这边确实在点击完同意才初始化的im。
我在插件的onAttachedToEngine中确实发现了mars初始化相关方法
    Mars.init(flutterPluginBinding.getApplicationContext(), handler);
但是这个方法调试好像并没有执行，打印也没有日志。
我想问一下 还没有用其他情况会自动执行 获取WIFI的BSSID

**Comment by imndx** [comment]
因为 IM 是需要保持长连接的，当网络变化时 ，可能需要重新连接 IM 服务。

网络变化，就需要获取```BSSID```等信息来判断，是否是切到了新的热点等。

**Comment by heavyrain2012** [comment]
我们再审查一下代码逻辑，可能需要几天时间得出结论

**Comment by heavyrain2012** [comment]
已经提交移除wifi权限的版本，注意在v1分支上

**Comment by qq1440214507** [comment]
好的 谢谢
