### ISSUE TITLE
关于getMessages 方法 Android和ios获取数据结果list是反的

### ISSUE THREAD

**Issue by qq1440214507** [wildfirechat/wfc_flutter_plugins#28]
我测试时发现FlutterImclient.getMessages方法，再ios和Android上返回的消息顺序是相反的

**Comment by heavyrain2012** [comment]
是v1分支，还是master分支？

**Comment by qq1440214507** [comment]
> 是v1分支，还是master分支？

三个月前的v1

**Comment by qq1440214507** [comment]
不知道新版本有没有这个问题，我在listview里面显示消息列表，然后发现Android和ios消息是反的

**Comment by heavyrain2012** [comment]
最新版本也是不一致的，我们刚更新了android的插件代码，把顺序调整为跟iOS一致了，请检查我们的提交

**Comment by qq1440214507** [comment]
好的谢谢
