### ISSUE TITLE
Demo无法运行

### ISSUE THREAD

**Issue by qq1440214507** [wildfirechat/wfc_flutter_plugins#30]
https://github.com/wildfirechat/wfc_flutter_plugins/blob/217fcf2541c84d1bc5318cb446d9dbb24704363e/example/lib/home.dart#L7
https://github.com/wildfirechat/wfc_flutter_plugins/blob/217fcf2541c84d1bc5318cb446d9dbb24704363e/example/lib/conversation_list_widget.dart#L6

这两行需要修改为
import 'package:flutter/material.dart' hide Badge;
才可以运行

**Comment by heavyrain2012** [comment]
是master分支吗？我测试了android和iOS不修改也可以运行啊？

**Comment by qq1440214507** [comment]
有没有可能是版本问题
