### ISSUE TITLE
新版本android发送语音消息成功后崩溃，实测可以收到，发送完毕就崩溃 android12

### ISSUE THREAD

**Issue by qq1440214507** [wildfirechat/wfc_flutter_plugins#33]
E/AndroidRuntime(30939): java.lang.AbstractMethodError: abstract method "void cn.wildfirechat.remote.SendMessageCallback.onMediaUpload(java.lang.String)"
E/AndroidRuntime(30939): 	at cn.wildfirechat.remote.ChatManager$16.lambda$onMediaUploaded$3(ChatManager.java:2477)
E/AndroidRuntime(30939): 	at cn.wildfirechat.remote.ChatManager$16$$ExternalSyntheticLambda4.run(Unknown Source:4)
E/AndroidRuntime(30939): 	at android.os.Handler.handleCallback(Handler.java:966)
E/AndroidRuntime(30939): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(30939): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(30939): 	at android.os.Looper.loop(Looper.java:293)
E/AndroidRuntime(30939): 	at android.app.ActivityThread.main(ActivityThread.java:9596)
E/AndroidRuntime(30939): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30939): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
E/AndroidRuntime(30939): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

**Comment by heavyrain2012** [comment]
已经解决，请更新验证

**Comment by qq1440214507** [comment]
> 已经解决，请更新验证

好的 谢谢
