### ISSUE TITLE
android启动报错

### ISSUE THREAD

**Issue by 657447158** [wildfirechat/wfc_flutter_plugins#34]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/25770737/217164349-9225cbcf-7241-4fb2-823c-f45c83dd1635.png">
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/25770737/217164552-a5b5ef1f-67af-4fd1-b9d7-96ab33bbdf47.png">

flutter版本3.3.4

**Comment by imndx** [comment]
请你在```mavenCentral() ```下面，添加如下配置试试：

       ``` maven { url 'https://jitpack.io' }```


https://github.com/wildfirechat/wfc_flutter_plugins/blob/5aab66686eedc6be7d5b895d3de87d3b9ba07b3b/rtckit/android/build.gradle#L18
