### ISSUE TITLE
初始化报null safety问题

### ISSUE THREAD

**Issue by 657447158** [wildfirechat/wfc_flutter_plugins#35]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/25770737/217738448-9cd352b9-eab4-48b1-9d70-2f113383a724.png">
按文档集成后，启动没问题，当调用初始化后Imclient.init() Rtckit.init() 时，报这个错误。

**Comment by qq1440214507** [comment]
flutter run apk --no-sound-null-safety 启动的时候加上 --no-sound-null-safety 这个就可以

**Comment by 657447158** [comment]
> > > flutter run apk --no-sound-null-safety 启动的时候加上 --no-sound-null-safety 这个就可以
> > 
> > 
> > 嗯，这个命令知道了。后续插件能否更新支持下null safety
> 
> 我也在等，得看官方进度了

我这边是启动起来后，初始化报了一堆错，你那边有遇到过吗？
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/25770737/217763045-be2386e6-82be-4608-a01d-085bd67bcb59.png">

**Comment by qq1440214507** [comment]
n

> > > > flutter run apk --no-sound-null-safety 启动的时候加上 --no-sound-null-safety 这个就可以
> > > 
> > > 
> > > 嗯，这个命令知道了。后续插件能否更新支持下null safety
> > 
> > 
> > 我也在等，得看官方进度了
> 
> 我这边是启动起来后，初始化报了一堆错，你那边有遇到过吗？ <img alt="image" width="1276" src="https://user-images.githubusercontent.com/25770737/217763045-be2386e6-82be-4608-a01d-085bd67bcb59.png">
需要在android app build.gradle中引入arr 比如下面，需要填写你自己的目录，我只用了client ，详细可以看一下example 下的android配置
    implementation fileTree(dir: "../../../wfc_flutter_plugins/android_client_aars", include: ["*.aar"])
