### ISSUE TITLE
上架异常,(SDK: TencentMar) 读取WIFI的BSSID

### ISSUE THREAD

**Issue by qq1440214507** [wildfirechat/wfc_flutter_plugins#36]
如上，上架百度和小米依然报这个，用的master分支最新代码，不能在插件初始化的时候获取WIFI的BSSID，希望在init 时读取

**Comment by imndx** [comment]
请你微信添加下：wfchat，他了解下情况，并协助解决。

**Comment by qq1440214507** [comment]
> wfchat

好的

**Comment by imndx** [comment]
#27 

### 开发建议：

用户首次进入 app 之后，弹出获取隐私信息（BSSID）确认框，用户确认之后，再进行 IM 连接操作。


### 需要获取```BSSID```的原因：

因为 IM 是需要保持长连接的，当网络变化时 ，可能需要重新连接 IM 服务。为了监听网络变化，就需要获取BSSID等信息来判断，是否是切到了新的热点等。
