### ISSUE TITLE
发消息崩溃了，下面是异常信息。

### ISSUE THREAD

**Issue by li8607** [wildfirechat/wfc_flutter_plugins#50]
Crashed: com.apple.main-thread
0  WFChatClient                   0x7b8c8 mars::app::GetAccountUserName() + 184
1  WFChatClient                   0x7b840 mars::app::GetAccountUserName() + 48
2  WFChatClient                   0x292f8 fillTMessage(mars::stn::TMessage&, WFCCConversation*, WFCCMessageContent*) + 188
3  WFChatClient                   0x28c3c -[WFCCIMService sendMedia:content:toUsers:expireDuration:success:progress:error:] + 1108
4  WFChatClient                   0x28798 -[WFCCIMService send:content:toUsers:expireDuration:success:error:] + 24
5  Runner                         0x4f5810 -[ImclientPlugin sendMessage:result:] + 395 (ImclientPlugin.m:395)
6  Runner                         0x4f2738 -[ImclientPlugin handleMethodCall:result:] + 29 (ImclientPlugin.m:29)
7  Flutter                        0x58e2e0 (缺少 UUID 4c4c446555553144a14939a372500a7c)
8  Flutter                        0x43858 (缺少 UUID 4c4c446555553144a14939a372500a7c)
9  libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
10 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
11 libdispatch.dylib              0x126a4 _dispatch_main_queue_drain + 928
12 libdispatch.dylib              0x122f4 _dispatch_main_queue_callback_4CF + 44
13 CoreFoundation                 0x98c28 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
14 CoreFoundation                 0x7a560 __CFRunLoopRun + 1992
15 CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
16 GraphicsServices               0x135c GSEventRunModal + 164
17 UIKitCore                      0x39d6e8 -[UIApplication _run] + 888
18 UIKitCore                      0x39d34c UIApplicationMain + 340
19 Runner                         0x6ca8 main + 6 (AppDelegate.swift:6)
20 ???                            0x1c083edec (缺少)

**Comment by heavyrain2012** [comment]
需要先connect，connect之后才可以进行各种业务操作

**Comment by heavyrain2012** [comment]
也有可能是多端登录被踢出，或者是被封禁，客户端协议栈退出状态，这个时候需要UI层监控连接状态，在连接状态变成logout/kickoff/reject等状态时退出到登录界面

**Comment by li8607** [comment]
好的
