### ISSUE TITLE
按集成文档集成后编译报错Error (Xcode): Undefined symbol: _OBJC_CLASS_$_WFAVEngineKit

### ISSUE THREAD

**Issue by TJRoger** [wildfirechat/wfc_flutter_plugins#51]
➜  ios git:(dev_im) ✗ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.4.1 22F82 darwin-arm, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.80.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by TJRoger** [comment]
必须得在rtckit 的 Build Phases手动链接才能通过编译
pod版本1.11.3

**Comment by heavyrain2012** [comment]
因为这个是动态库，所以需要embed才行

**Comment by liaovq** [comment]
我这边也有同样的问题，应该如何配置？
