### ISSUE TITLE
flutter sdk部分接口报错

### ISSUE THREAD

**Issue by functionName** [wildfirechat/wfc_flutter_plugins#54]
Imclient.getFavGroups()
Imclient.setConversationTop()
Imclient.setFavGroup()
还有一些邀请群好友等接口 直接调用就会出错 
插件中example 可以直接调用这几个接口并传入参数 会报错java.lang.reflect.InvocationTargetException

**Comment by functionName** [comment]
我这边是安卓环境

**Comment by heavyrain2012** [comment]
Imclient.getFavGroups()
Imclient.setConversationTop()
这2个问题已经解决。

Imclient.setFavGroup() 这个测试没有发现崩溃，请用最新再验证一下，如果还有请把参数贴出来看一下。

还有一些邀请群好友等接口 直接调用就会出错 这个我测试了在群中添加成员，没有发现出错，请确认
