### ISSUE TITLE
flutter部分event未处理以及BUG

### ISSUE THREAD

**Issue by functionName** [wildfirechat/wfc_flutter_plugins#55]
friendListUpdatedCallback 这个callback没有执行。
我看你们的源码里面 方法名叫 onUserInfoUpdated 。但是调用方法使用的onUserInfoUpdate 少了一个d。
还有一些类似的比如 onUserInfoUpdated 调用方法使用的 onUserInfoUpdate

![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/46063523/d0d05936-debb-4ed4-a21d-520c5ea42a7e)
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/46063523/747e8d3e-de5b-4ceb-aea5-14a38e15d545)

**Comment by functionName** [comment]
searchUser这个方法搜索好像有问题，我searchType传入1，应该是精准搜索name和mobile，但是不管我搜索手机号或者name这个字段。搜索出来永远是空的列表。
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/46063523/de717ee9-075a-4f6d-af1e-1f272e4cf457)
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/46063523/1144427c-0fb1-4201-84ff-769c3eacc350)

**Comment by functionName** [comment]
Imclient.getUserInfo 获取不到mobile这个字段。永远获取出来都是null，应该是映射错误了

**Comment by functionName** [comment]
> searchUser这个方法搜索好像有问题，我searchType传入1，应该是精准搜索name和mobile，但是不管我搜索手机号或者name这个字段。搜索出来永远是空的列表。 ![image](https://user-images.githubusercontent.com/46063523/258288337-de717ee9-075a-4f6d-af1e-1f272e4cf457.png) ![image](https://user-images.githubusercontent.com/46063523/258288463-1144427c-0fb1-4201-84ff-769c3eacc350.png)

![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/46063523/4af38eef-d3c5-4df6-aa05-6b749748e3ee)
这是我调用的代码

**Comment by heavyrain2012** [comment]
> friendListUpdatedCallback 这个callback没有执行。 我看你们的源码里面 方法名叫 onUserInfoUpdated 。但是调用方法使用的onUserInfoUpdate 少了一个d。 还有一些类似的比如 onUserInfoUpdated 调用方法使用的 onUserInfoUpdate
> 
> ![image](https://user-images.githubusercontent.com/46063523/258285493-d0d05936-debb-4ed4-a21d-520c5ea42a7e.png) ![image](https://user-images.githubusercontent.com/46063523/258285542-747e8d3e-de5b-4ceb-aea5-14a38e15d545.png)

已经提交，请更新验证

**Comment by heavyrain2012** [comment]
> Imclient.getUserInfo 获取不到mobile这个字段。永远获取出来都是null，应该是映射错误了

已提交，请验证

> > searchUser这个方法搜索好像有问题，我searchType传入1，应该是精准搜索name和mobile，但是不管我搜索手机号或者name这个字段。搜索出来永远是空的列表。 ![image](https://user-images.githubusercontent.com/46063523/258288337-de717ee9-075a-4f6d-af1e-1f272e4cf457.png) ![image](https://user-images.githubusercontent.com/46063523/258288463-1144427c-0fb1-4201-84ff-769c3eacc350.png)
> 
> ![image](https://user-images.githubusercontent.com/46063523/258288783-4af38eef-d3c5-4df6-aa05-6b749748e3ee.png) 这是我调用的代码

static void searchUser(
      String keyword,
      int searchType,
      int page,
      OperationSuccessUserInfosCallback successCallback,
      OperationFailureCallback errorCallback)
搜索函数一次搜索返回20个用户，第三个参数是page，用来翻页的，你应用用0才对
