### ISSUE TITLE
MissingPluginException(No implementation found for method getClientId on channel imclient)

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#56]
真机调试的时候一切正常，但是如果flutter build apk打包apk以后，手机安装运行，点击登录，会抛出这个错误
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/14b77730-80c7-456e-beaf-bfe8996521db)
<img width="1305" alt="a538513fa8eb1c90f1bf8b4edffbd5a" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/e1b728af-4b2b-4544-88b1-293c785e1dab">

**Comment by heavyrain2012** [comment]
用我们demo打包后是正常的吗？另外你从网上找找看有没有类似的问题

**Comment by li460930736** [comment]
> 用我们demo打包后是正常的吗？另外你从网上找找看有没有类似的问题

![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/095bd0b8-b110-47cf-982c-b9daf3da6309)
已经解決，原來是缺少了这个文件，所以导致开发的时候正常，打包以后丢失了方法

**Comment by imndx** [comment]
> > 用我们demo打包后是正常的吗？另外你从网上找找看有没有类似的问题
> 
> ![image](https://user-images.githubusercontent.com/56672001/265861941-095bd0b8-b110-47cf-982c-b9daf3da6309.png) 已经解決，原來是缺少了这个文件，所以导致开发的时候正常，打包以后丢失了方法

是的，这个文件是混淆相关的，非常重要，不包含的话，会导致方法被混淆，进而崩溃。
