### ISSUE TITLE
createGroup方法创建群聊失败

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#57]
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/8dc25354-165e-4191-aeea-2b729e9125b1)
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/75ddd7d8-b9f0-42f9-9d09-ac8707be9fe5)
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/6b447c7d-8b00-43be-b289-12850681bae8)
参数：群id为null，群名字string，群头像string是一个url，members是一个List<string>，里面是userId，我选中了1个好友或者2个好友，都报这个错误，断点没有走进error或者success的回调，请问一下是哪里使用错误了吗

**Comment by heavyrain2012** [comment]
我们已经确认了这个问题，正在处理，请稍等
