### ISSUE TITLE
demo运行pub get失败，依赖跟sdk冲突了

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#58]
![e8273546cf098bc4b9ff3da0713591e](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/8078d22e-c6f6-48f1-a29a-617cf167a5bd)
![9597102d54c78fed87cde811feca6f1](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/8a8effeb-f17a-41cb-931d-327068f8201d)

**Comment by heavyrain2012** [comment]
修改一下版本试试
