### ISSUE TITLE
Imclient.IMEventBus 收不到任何消息

### ISSUE THREAD

**Issue by liaovq** [wildfirechat/wfc_flutter_plugins#59]
按照文档进行了以下步骤
1. Rtckit.init();
2. Imclient.init(...);
3. login
4. Imclient.connect(...);
5. await Imclient.getConversationInfos();
6. final EventBus _eventBus = Imclient.IMEventBus;
7. 注册了ConnectionStatusChanged、ReceiveMessages、UserSettingUpdated、RecallMessage等消息的监听
获取到对话列表之后，有新消息来的时候，不会走listen的回掉，请问IMEventBus是少注册了哪一步吗？目前无法收到任何消息

**Comment by liaovq** [comment]
<img width="1483" alt="Snipaste_2023-09-08_14-23-52" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/74915079/baba6c83-5924-4fdd-9bd0-5fce152b0b2b">
右侧原生的代码执行后，左侧 flutter 端的回调并没有执行，

**Comment by liaovq** [comment]
找到问题了，只要按照 fcm 接入的文档配置了 onBackgroundMessage 就一定收不到消息，去掉之后就好了。
<img width="930" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/74915079/389a273e-e119-467d-8ffb-50806c699a52">

https://firebase.google.com/docs/cloud-messaging/flutter/receive?hl=zh-cn

**Comment by li460930736** [comment]
你好，我貌似遇到了跟你类似的问题，但是我是debug包正常，release包不执行回调了，请问你有发生这种情况吗？

**Comment by li8607** [comment]
> 你好，我貌似遇到了跟你类似的问题，但是我是debug包正常，release包不执行回调了，请问你有发生这种情况吗？

遇到过，build.gradle配置不对。

**Comment by imndx** [comment]
https://github.com/firebase/flutterfire/issues/9689
