### ISSUE TITLE
打包后的Imclient.init，收到消息后，没有触发回调

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#60]
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/4b4be68b-be59-43cd-86b9-efe74f9db026)
如图所示，实机开发调试的时候，收到消息会弹出消息提示，但是打包安卓apk安装以后，则没有任何提示，并没有触发回调

**Comment by li460930736** [comment]
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/0456712d-1fba-4a3c-98ce-dfbe4b1d110b)
app-debug.apk是正常的，app-release.apk则不行，混淆文件已经加了

**Comment by imndx** [comment]
可能还是混淆的问题

**Comment by li460930736** [comment]
> 可能还是混淆的问题
是复制的example里android文件夹的，没有经过改动

**Comment by li460930736** [comment]
> 可能还是混淆的问题
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/fea4acd7-7654-48b0-95e4-e5a9fb88e379)

![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/b0c57879-aeea-4432-91cc-f954634732be)
甚至尝试在这里写了try catch，可是release包也没有反应，只有debug包有反应

**Comment by imndx** [comment]
你构建的时候，禁止混淆试试:

`flutter build apk --no-shrink`

FYI:
https://www.jianshu.com/p/4dd5e5977f36

**Comment by li460930736** [comment]
> 你构建的时候，禁止混淆试试:
> 
> `flutter build apk --no-shrink`
> 
> FYI: https://www.jianshu.com/p/4dd5e5977f36

![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/4cc5756b-79cd-4495-b80b-6f486e79a26e)
非常感谢，我尝试这种方法关闭混淆以后，打包以后正常运行了，打出来的包比原来大了1M左右

**Comment by imndx** [comment]
OK，我们研究下混淆相关配置。
