### ISSUE TITLE
能用 flutter plugins 来作为web 开发的项目吗？

### ISSUE THREAD

**Issue by huazaihuola** [wildfirechat/wfc_flutter_plugins#62]
目前是用vue 开发，但是付费版成本暂时支付不起，想使用当前组件 flutter plugins 来开发web 内容，UI  我自己准备好了，毕竟要求不是很高的复杂功能，只需要接收通知，发送消息。

想问一下，这块能行不，有没有老哥做出来过，或者还有什么其他解决方案？

**Comment by imndx** [comment]
不支持，flutter 版的通讯能力是通过原生插件实现的。
