### ISSUE TITLE
关于申请加群的api

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#63]
请问有没有申请加群的，我只看到有addGroupMembers邀请成员入群的api，没看到有相关的申请加群，还有接受或者拒绝申请相关的api

**Comment by heavyrain2012** [comment]
野火目前只有直接加群的接口，没有其他功能。如果需要实现你们的业务逻辑，需要做二次开发，比如加群这个功能，可以在应用服务或者其他服务实现，后面简称业务服务，当客户端要求加群时，调用到业务服务，业务服务根据自身的逻辑来决定是直接把用户拉入群中，或则直接拒绝，或者给出问题，答对就加入，或者给群主或者群管理发通知消息。群主或者群管理看到加群审批通知有，点允许或者拒绝，允许时业务服务把用户加入到群中

**Comment by heavyrain2012** [comment]
有个文章 https://docs.wildfirechat.cn/blogs/加群验证功能.html 请参考一下

**Comment by li460930736** [comment]
> 野火目前只有直接加群的接口，没有其他功能。如果需要实现你们的业务逻辑，需要做二次开发，比如加群这个功能，可以在应用服务或者其他服务实现，后面简称业务服务，当客户端要求加群时，调用到业务服务，业务服务根据自身的逻辑来决定是直接把用户拉入群中，或则直接拒绝，或者给出问题，答对就加入，或者给群主或者群管理发通知消息。群主或者群管理看到加群审批通知有，点允许或者拒绝，允许时业务服务把用户加入到群中

好的，明白了，谢谢
