### ISSUE TITLE
关于点击通知栏消息自动跳转

### ISSUE THREAD

**Issue by 657447158** [wildfirechat/wfc_flutter_plugins#64]
我们集成了个推，在消息送到，点击通知后，自动跳转到了野火的UI聊天界面，我需要跳转到自定义的界面。这个如何实现呢？

**Comment by imndx** [comment]
现在有问题的是：

应用在后台运行，收到消息之后，通知栏有提示，点击通知，跳转到了野火的UI 聊天页面？

还是，应用被杀死，没有在运行，收到通过个推推送过来的通知，点击通知，跳转到了野火的 UI 聊天页面？

**Comment by 657447158** [comment]
现在测试的是应用在后台运行。我们是用频道推送的。然后调到了野火的 系统通知 这个UI界面

**Comment by imndx** [comment]
那应用被杀之后的推送通知正常吗？

**Comment by 657447158** [comment]
杀死之后点通知，点通知 直接进到的是主页面，好像个推那里的回调也是没反应。

**Comment by imndx** [comment]
414fcc4

我们将野火Android 端原生的通知处理逻辑禁用了，你们需要在应用层，自行处理通知逻辑，比如：应用在后台的时候，收到消息，需要弹出通知，然后点击通知，需要跳转到你们的页面。

**Comment by 657447158** [comment]
我们是在哪里能监听到这个收到通知，点击通知的回调呢?

**Comment by imndx** [comment]
`ReceiveMessageCallback`

**Comment by li460930736** [comment]
你好，我也遇到了相同的问题，我用的是极光推送，华为通道，挂载后台以后，收到消息通知，点击消息通知，打开的是野火的私聊页面，而不是自己的app应用首页，请问你那边解决了这个问题吗？

**Comment by li460930736** [comment]
> `ReceiveMessageCallback`

这个是收到消息后的回调，并非点击推送消息通知的回调，请问如何点击推送消息通知以后，打开APP某页？

**Comment by imndx** [comment]
> 你好，我也遇到了相同的问题，我用的是极光推送，华为通道，挂载后台以后，收到消息通知，点击消息通知，打开的是野火的私聊页面，而不是自己的app应用首页，请问你那边解决了这个问题吗？

你更新到最新代码，就不会打开野火的私聊页面了，这时需要你们在`ReceiveMessageCallback`回调里面处理，应用在后台时的推送逻辑；

具体到打开具体的页面，需要`flutter`层处理，可以下[这儿](https://szuwest.github.io/tag/flutter-tui-song-tong-zhi-xin-ge.html)

**Comment by li460930736** [comment]
> > 你好，我也遇到了相同的问题，我用的是极光推送，华为通道，挂载后台以后，收到消息通知，点击消息通知，打开的是野火的私聊页面，而不是自己的app应用首页，请问你那边解决了这个问题吗？
> 
> 你更新到最新代码，就不会打开野火的私聊页面了，这时需要你们在`ReceiveMessageCallback`回调里面处理，应用在后台时的推送逻辑；
> 
> 具体到打开具体的页面，需要`flutter`层处理，可以下[这儿](https://szuwest.github.io/tag/flutter-tui-song-tong-zhi-xin-ge.html)

谢谢回复，我刚更新了以后，挂后台，私聊消息推送没有了，语音视频通话推送还是正常。您的意思是需要我在ReceiveMessageCallback回调里面，区分应用前后台状态，然后开启本地推送是吗？我尝试按这个逻辑实现了，但是还不清楚安卓的电池策略是否会有影响，例如长时间挂到后台，会把进程杀掉之类的。

**Comment by li460930736** [comment]
> > 你好，我也遇到了相同的问题，我用的是极光推送，华为通道，挂载后台以后，收到消息通知，点击消息通知，打开的是野火的私聊页面，而不是自己的app应用首页，请问你那边解决了这个问题吗？
> 
> 你更新到最新代码，就不会打开野火的私聊页面了，这时需要你们在`ReceiveMessageCallback`回调里面处理，应用在后台时的推送逻辑；
> 
> 具体到打开具体的页面，需要`flutter`层处理，可以下[这儿](https://szuwest.github.io/tag/flutter-tui-song-tong-zhi-xin-ge.html)

可是我发现，挂在后台时间长一点以后，进程会被杀死，ReceiveMessageCallback回调也是不会触发

**Comment by li460930736** [comment]
> > > 你好，我也遇到了相同的问题，我用的是极光推送，华为通道，挂载后台以后，收到消息通知，点击消息通知，打开的是野火的私聊页面，而不是自己的app应用首页，请问你那边解决了这个问题吗？
> > 
> > 
> > 你更新到最新代码，就不会打开野火的私聊页面了，这时需要你们在`ReceiveMessageCallback`回调里面处理，应用在后台时的推送逻辑；
> > 具体到打开具体的页面，需要`flutter`层处理，可以下[这儿](https://szuwest.github.io/tag/flutter-tui-song-tong-zhi-xin-ge.html)
> 
> 可是我发现，挂在后台时间长一点以后，进程会被杀死，ReceiveMessageCallback回调也是不会触发

我明白了，貌似需要我允许后台活动权限，就可以不被杀死进程

**Comment by imndx** [comment]
> > > > 你好，我也遇到了相同的问题，我用的是极光推送，华为通道，挂载后台以后，收到消息通知，点击消息通知，打开的是野火的私聊页面，而不是自己的app应用首页，请问你那边解决了这个问题吗？
> > > 
> > > 
> > > 你更新到最新代码，就不会打开野火的私聊页面了，这时需要你们在`ReceiveMessageCallback`回调里面处理，应用在后台时的推送逻辑；
> > > 具体到打开具体的页面，需要`flutter`层处理，可以下[这儿](https://szuwest.github.io/tag/flutter-tui-song-tong-zhi-xin-ge.html)
> > 
> > 
> > 可是我发现，挂在后台时间长一点以后，进程会被杀死，ReceiveMessageCallback回调也是不会触发
> 
> 我明白了，貌似需要我允许后台活动权限，就可以不被杀死进程

是的，需要后台活动权限，但极端情况下，还是可能被杀死，这种情况下，就需要对接推送。

**Comment by tomsyb** [comment]
> > > > > 你好，我也遇到了相同的问题，我用的是极光推送，华为通道，挂载后台以后，收到消息通知，点击消息通知，打开的是野火的私聊页面，而不是自己的app应用首页，请问你那边解决了这个问题吗？
> > > > 
> > > > 
> > > > 你更新到最新代码，就不会打开野火的私聊页面了，这时需要你们在`ReceiveMessageCallback`回调里面处理，应用在后台时的推送逻辑；
> > > > 具体到打开具体的页面，需要`flutter`层处理，可以下[这儿](https://szuwest.github.io/tag/flutter-tui-song-tong-zhi-xin-ge.html)
> > > 
> > > 
> > > 可是我发现，挂在后台时间长一点以后，进程会被杀死，ReceiveMessageCallback回调也是不会触发
> > 
> > 
> > 我明白了，貌似需要我允许后台活动权限，就可以不被杀死进程
> 
> 是的，需要后台活动权限，但极端情况下，还是可能被杀死，这种情况下，就需要对接推送。



> > > > > 你好，我也遇到了相同的问题，我用的是极光推送，华为通道，挂载后台以后，收到消息通知，点击消息通知，打开的是野火的私聊页面，而不是自己的app应用首页，请问你那边解决了这个问题吗？
> > > > 
> > > > 
> > > > 你更新到最新代码，就不会打开野火的私聊页面了，这时需要你们在`ReceiveMessageCallback`回调里面处理，应用在后台时的推送逻辑；
> > > > 具体到打开具体的页面，需要`flutter`层处理，可以下[这儿](https://szuwest.github.io/tag/flutter-tui-song-tong-zhi-xin-ge.html)
> > > 
> > > 
> > > 可是我发现，挂在后台时间长一点以后，进程会被杀死，ReceiveMessageCallback回调也是不会触发
> > 
> > 
> > 我明白了，貌似需要我允许后台活动权限，就可以不被杀死进程
> 
> 是的，需要后台活动权限，但极端情况下，还是可能被杀死，这种情况下，就需要对接推送。

你好，目前我们集成的个推，插件已更新到最新版本，出现通知栏没得消息，通知栏显示也需要自己构造是不。

**Comment by imndx** [comment]
> 你好，目前我们集成的个推，插件已更新到最新版本，出现通知栏没得消息，通知栏显示也需要自己构造是不。

是的，通知栏显示需要自己处理，是在前面说的`ReceiveMessageCallback`里面处理，需要判断下当前是不是在后台运行，是的话，显示一个通知。

**Comment by tomsyb** [comment]
> > 你好，目前我们集成的个推，插件已更新到最新版本，出现通知栏没得消息，通知栏显示也需要自己构造是不。
> 
> 是的，通知栏显示需要自己处理，是在前面说的`ReceiveMessageCallback`里面处理，需要判断下当前是不是在后台运行，是的话，显示一个通知。

你好，离线厂商推过来，点击通知跳转到具体界面的情况，是需要我自己处理推送穿过来的东西决定跳转（比如android自己解析intent），还是说离线点击通知后启动APP ReceiveMessageCallback会收到点击的哪个离线消息进而跳转具体界面
