### ISSUE TITLE
朋友圈特出需求

### ISSUE THREAD

**Issue by 1771893348** [wildfirechat/wfc_flutter_plugins#65]
我们有个组织架构，朋友圈要显示所有组织架构中成员的朋友圈动态

**Comment by heavyrain2012** [comment]
已经支持全局朋友圈功能，请更新验证

**Comment by 1771893348** [comment]
更新哪个项目，后台还是服务器，怎么操作，咱们有文档吗

**Comment by heavyrain2012** [comment]
更新IM服务，添加了一个配置(moments.global_visible)，打开这个配置就可以了
