### ISSUE TITLE
发送图片朋友圈失败

### ISSUE THREAD

**Issue by 1771893348** [wildfirechat/wfc_flutter_plugins#66]
图片发送不成功，错误信息
E/flutter (21710): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument: Instance of 'FeedEntry'
E/flutter (21710): #0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:466:7)
E/flutter (21710): #1      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:456:9)
E/flutter (21710): #2      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:463:9)
E/flutter (21710): #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
E/flutter (21710): #4      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:461:13)
E/flutter (21710): #5      StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:604:18)
E/flutter (21710): #6      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:304:34)
E/flutter (21710): #7      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:491:12)
E/flutter (21710): #8      MethodChannelMomentClient.postFeed (package:momentclient/momentclient_method_channel.dart:201:52)
E/flutter (21710): #9      MomentClient.postFeed (package:momentclient/momentclient.dart:105:47)
E/flutter (21710): #10     _SendPhotoState.build.<anonymous closure> (package:renda/imclient/circles/sendPhoto.dart:72:32)
E/flutter (21710): <asynchronous suspension>
E/flutter (21710):

**Comment by heavyrain2012** [comment]
发送图片朋友圈，需要先上传图片，得到链接之后再发送朋友圈
