### ISSUE TITLE
关于视频语音通话后的奇怪现象

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#68]
![151bc5eac97b1f17367b0ee38d34786](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/016786de-cef6-4f86-b217-6e0564464662)
进行视频语音通话以后，挂断，安卓手机会出现对面发出一大堆空信息的状况，然后后退再重新进来页面，则正常。苹果手机则不会出现这种情况。貌似是因为ReceiveMessageCallback里面写了回调，安卓的视频语音通话触发了这个回调，返回的未知类型的message导致的。

**Comment by li460930736** [comment]
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/9192a850-89ef-4c2e-a7d0-10e960904661)
实测如果callback里面debug，语音通话会触发ReceiveMessageCallback回调

**Comment by li460930736** [comment]
我已经让未知类型的消息不进行回调渲染到页面，但不了解为什么安卓视频语音通话会出现触发ReceiveMessageCallback这种情况，而ios不会

**Comment by imndx** [comment]
> 我已经让未知类型的消息不进行回调渲染到页面，但不了解为什么安卓视频语音通话会出现触发ReceiveMessageCallback这种情况，而ios不会

正常应当根据存储类型来决定是否显示，未知消息有的时候是需要显示的，比如对方发了一个己方尚不支持，或者未注册的存储并计数消息。

由于需要存储的消息的`messageId`都是非 0，也可以通过`messageId !=0`来过滤


至于为什么只有 Android 触发了音视频通话信令消息回调，请 @heavyrain2012 确认下

**Comment by heavyrain2012** [comment]
iOS会过滤掉音视频的消息，这个问题上层过滤一下就好了，把messageId为0的消息忽略掉
