### ISSUE TITLE
获取自己发送的好友请求，返回的结果错误

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#69]
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/5140c0f1-1c5a-420b-9041-11a26682030e)
这两个api，一个是收到的好友请求，一个是自己发送的好友请求，可是2个api得到的结果都是收到的好友请求。

**Comment by li460930736** [comment]
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/0dbfac16-f043-4c39-a3e0-a563a5fc394e)
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/0759a799-e3a4-4e73-91a9-366a7dae1ce1)
两个api返回的都是收到的好友请求

**Comment by heavyrain2012** [comment]
已经解决，请更新到最新验证
