### ISSUE TITLE
想请问一下关于视频语音通话

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#70]
你好，我想问一下，怎么能实现微信那种，一方APP挂在后台，然后另一方对其发起视频或者语音通话以后，挂在后台的那一方，可以震动+屏幕直接弹出拒绝和接听，类似微信那种效果。这是关于推送的业务还是关于视频通话方面的业务呢？

**Comment by heavyrain2012** [comment]
这个是推送的业务，对接推送就可以了
