### ISSUE TITLE
关于本地聊天记录和历史聊天记录的问题

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#71]
你好，我想请问一下，取聊天记录，getMessages能否像取userInfo一样，强制从远程拉取，因为有时候卸载了app重新安装或者清了缓存，会导致聊天记录都没了。而getRemoteMessages里的beforeMessageUid，由于本地记录都清空了，没办法从头再重新获取一遍
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/ff7a588e-72ae-44ee-ac49-a055a91ccc1c)

**Comment by li460930736** [comment]
经常发生用户卸载了app以后，重新安装，就没了聊天记录，是否有同步远程聊天记录的api呢？？

**Comment by li460930736** [comment]
已经解决，原来是服务器端参数设置，跟客户端无关
![1207b9928746602dcc880d1df68987f](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/acfcafda-a6cd-4e74-aa1c-684f4ac9a18f)

**Comment by heavyrain2012** [comment]
👌
