### ISSUE TITLE
集成 imclient 后，跟定位等权限有冲突。我这边调用定位，本地存储 都会奔溃

### ISSUE THREAD

**Issue by SummerZZ100** [wildfirechat/wfc_flutter_plugins#72]

**Comment by SummerZZ100** [comment]
E/flutter ( 3064): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 3064): 
I/om.zxs.moca_on( 3064): ProcessProfilingInfo new_methods=1444 is saved saved_to_disk=1 resolve_classes_delay=8000

**Comment by SummerZZ100** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)

**Comment by liaovq** [comment]
同样的问题
