### ISSUE TITLE
集成 imclient 后，android端定位等权限有冲突 MissingPluginException PlatformException

### ISSUE THREAD

**Issue by SummerZZ100** [wildfirechat/wfc_flutter_plugins#73]
集成 imclient 后，android端定位等权限有冲突。调用定位，本地存储 都会奔溃

E/flutter ( 3064): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null) E/flutter ( 3064): I/om.zxs.moca_on( 3064): ProcessProfilingInfo new_methods=1444 is saved saved_to_disk=1 resolve_classes_delay=8000

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)

**Comment by imndx** [comment]
这应当不是我们插件的问题，这个报错，也不是我们插件，你再查一下：

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
```

**Comment by imndx** [comment]
FYI：https://github.com/Baseflow/flutter-permission-handler/issues/586

**Comment by SummerZZ100** [comment]
现在是 我引入你们插件就会报这个错。不引入程序运行非常正常

**Comment by SummerZZ100** [comment]
感觉你们这个Flutter插件有好多问题 能不能用 😂

**Comment by imndx** [comment]
能用的，很多客户都在用的。

要不，请你做一个最小能复现这个问题的 demo，然后我们调试下。

**Comment by SummerZZ100** [comment]
可以，您能否加我微信 ：15810212304

**Comment by SummerZZ100** [comment]
> 能用的，很多客户都在用的。
> 
> 要不，请你做一个最小能复现这个问题的 demo，然后我们调试下。

您能否加我微信 ：15810212304

**Comment by liaovq** [comment]
同样的问题

**Comment by imndx** [comment]
> 同样的问题

是集成的问题，看下 readme 的说明

**Comment by liaovq** [comment]
> > 同样的问题
> 
> 是集成的问题，看下 readme 的说明

看了几十遍了，上面提到的该配的都配了

**Comment by imndx** [comment]
特别关注这部分，如果确认的话，附上日志，我们看下

```
   dependencies {

     // 将path_to_android_xxx_aars 替换成实际路径，可以使用相对路径，但一定要保证路径是正确的；路径不对的话，会报 ClassNotFoundException
     // wfc dep start

     // 根据实际需要，引入aar

     implementation fileTree(dir: "${path_to_android_client_aars}", include: ["*.aar"])
     implementation fileTree(dir: "${path_to_android_uikit_aars}", include: ["*.aar"])
     //implementation fileTree(dir: "${path_to_android_moment_aars}", include: ["*.aar"])
     //implementation fileTree(dir: "${path_android_ptt_aars}", include: ["*.aar"])

     // wfc dep end
 }

```

**Comment by liaovq** [comment]
和你们 example 对比配置，找了两天了，没看到哪里有什么不同

**Comment by imndx** [comment]
那你更新一下那些```aar```文件试下

**Comment by liaovq** [comment]
可以了，更新的时候这里漏掉了，谢谢
