### ISSUE TITLE
关于Imclient.getMessages返回的List<Message>能否带上消息人的UserInfo？

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#74]
你好，我发现这个api返回的只有userId，需要遍历再用getUserInfo查用户信息才能拿到头像和名字展示在页面上，请问能否直接能拿到相关信息？

**Comment by heavyrain2012** [comment]
数据是分别分开的，没有办法获取消息的时候同时把用户信息返回，可以分开获取
