### ISSUE TITLE
最新版本，安卓端，聊天键盘，输入框输入文字就会报个异常，但不影响正常聊天

### ISSUE THREAD

**Issue by moQingTing** [wildfirechat/wfc_flutter_plugins#76]
D/InsetsController(26115): show(ime(), fromIme=true)
E/flutter (26115): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
E/flutter (26115): #0      ImclientPlatform._convertProtoMessage (package:imclient/imclient_method_channel.dart:756:9)
E/flutter (26115): #1      ImclientPlatform.sendMediaMessage (package:imclient/imclient_method_channel.dart:1829:23)
E/flutter (26115): <asynchronous suspension>
E/flutter (26115): 
I/IMM_LC  (26115): showSoftInput(View,I)
I/IMM_LC  (26115): ssi() - flag : 0 view : cn.wildfirechat.chat reason = SHOW_SOFT_INPUT
I/IMM_LC  (26115): ssi() view is not EditText

**Comment by heavyrain2012** [comment]
已经解决，请检查 https://github.com/wildfirechat/wfc_flutter_plugins/commit/c6ae63a7ad3b18c2bf06ea95cf61c6d9fb7fd94f
