### ISSUE TITLE
发现监听的发送回执和已读事件并不执行，或者是我不知道什么时候会执行

### ISSUE THREAD

**Issue by moQingTing** [wildfirechat/wfc_flutter_plugins#77]
发现监听的发送回执和已读事件并不执行，或者是我不知道什么时候会执行
 _deliveryMessageSubscription = _eventBus.on<MessageDeliveriedEvent>().listen((event) {
      _handleMessageDelivery(event.deliveryMap);
    });

    _readMessageSubscription = _eventBus.on<MessageReadedEvent>().listen((event) {
      _handleMessageRead(event.readedReports);
    });
关于已读的处理，能否出一个demo给我？谢谢

**Comment by imndx** [comment]
你好，消息回执，需要专业版 im-server 才支持。

**Comment by heavyrain2012** [comment]
专业版IM服务还需要在配置文件中打开

**Comment by moQingTing** [comment]
> 专业版IM服务还需要在配置文件中打开

谢谢告知
