### ISSUE TITLE
群聊发送 at 消息收不到对应的 unreadMention

### ISSUE THREAD

**Issue by liaovq** [wildfirechat/wfc_flutter_plugins#78]
发送消息时
```
        txt.mentionedType = 1;
        txt.mentionedTargets = getMentionedUserIds(text);
```
然后上面对应的 userId 那个号 Conversation 上的 unreadMention 一直是 0
```
conversationInfo.unreadCount.unreadMention
```

**Comment by imndx** [comment]
最新代码无法复现
<img width="903" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/34434072/8109e195-b007-46eb-8c90-e33ad786150b">

**Comment by liaovq** [comment]
更新代码后依旧不行
发送的代码有什么问题吗
```
txt.mentionedType = 1;
txt.mentionedTargets = getMentionedUserIds(text);
```

**Comment by imndx** [comment]
看起来没什么问题，你可以打印看下`mentionedTargets`的值，这应当是个数组，包含群里面，所有要@的群成员的用户 id

**Comment by liaovq** [comment]
发消息时，如果有at相关内容，会在发消息时做
```
txt.mentionedType = 1;
txt.mentionedTargets = getMentionedUserIds(text);
```
以下是相关日志
<img width="891" alt="Snipaste_2023-11-09_13-49-24" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/74915079/0199335f-e990-4767-84ea-a78733076580">
接收消息时，如果有 at 那么接收到的内容是没有 mentioned 的相关信息
<img width="1024" alt="Snipaste_2023-11-09_13-52-22" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/74915079/c9e24132-f4d7-4113-98ba-e5380b516107">
