### ISSUE TITLE
撤回消息没有回调

### ISSUE THREAD

**Issue by liaovq** [wildfirechat/wfc_flutter_plugins#79]
调用 Imclient.recallMessage 之后，传入的两个参数，成功和失败的回调都不会执行
```
  ///撤回消息
  static void recallMessage(
      int messageUid,
      OperationSuccessVoidCallback successCallback,
      OperationFailureCallback errorCallback) async {
    ImclientPlatform.instance.recallMessage(messageUid, successCallback, errorCallback);
  }

```

**Comment by imndx** [comment]
你好，用 demo 测试了一下，能够走到成功回调，请用最新 demo 确认一下

**Comment by liaovq** [comment]
更新代码后依旧不行，成功和失败的回调依然没走，console里也没有报错
<img width="744" alt="Snipaste_2023-11-08_10-44-42" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/74915079/99e884de-98e9-4fce-a690-f2fd01b141bf">

**Comment by imndx** [comment]
请直接用 demo 测试下

**Comment by liaovq** [comment]
目前支持去除撤回的时间限制吗，比如我要撤回自己很久之前的，以及群主撤回任何消息

**Comment by liaovq** [comment]
我看了代码的实现在 client-release.aar 里

**Comment by imndx** [comment]
z

> 目前支持去除撤回的时间限制吗，比如我要撤回自己很久之前的，以及群主撤回任何消息

支持，将 im-server 更新到最新，然后看下 im-server 的配置。

撤回自己的消息的时间限制，需要客户单和 im-server 配合修改，客户端的配置不能长于 im-server 的配置

**Comment by liaovq** [comment]
好的，谢谢
