### ISSUE TITLE
输入状态的问题

### ISSUE THREAD

**Issue by doralines** [wildfirechat/wfc_flutter_plugins#87]
我看你们有个提交版本是说 关闭了原生通知的逻辑，让开发者在flutter端自行实现逻辑，现在遇到几个问题
1.我们接入了输入状态，但是输入状态每次发送也会触发 ConversationUpdate 这个通知，但是并不会出现在 TypingMessageContent 并不会出现在 lastMessage 中。
2.因为1这个问题 我们的通知逻辑本身是只要触发了 ConversationUpdate 并且不处于免打扰状态 就会提示用户，现在我们会因为触发了 问题1 而导致消息通知会错误
3.新添加的好友 在线状态不准确的问题。这个还没有对应的回复

**Comment by heavyrain2012** [comment]
1.我们接入了输入状态，但是输入状态每次发送也会触发 ConversationUpdate 这个通知，但是并不会出现在 TypingMessageContent 并不会出现在 lastMessage 中。

因为消息是状态消息，只有在线收，不在线抛弃，且不存储，所以不会在lastMessage中，实际上也不应该有 ConversationUpdate 的通知，UI层需要监听消息，如果收到 TypingMessageContent 来显示正在输入。

2.因为1这个问题 我们的通知逻辑本身是只要触发了 ConversationUpdate 并且不处于免打扰状态 就会提示用户，现在我们会因为触发了 问题1 而导致消息通知会错误

见上一条回复，需要监听收到新消息，如果收到了 TypingMessageContent 显示正在输入

3.新添加的好友 在线状态不准确的问题。这个还没有对应的回复

这个是IM服务的问题，已经修正，请发邮件给我们更新版本

**Comment by doralines** [comment]
还有个问题 就是每次你们给我新的IM包的时候 我只需要替换哪些东西就可以正常运行，不全部替换有的时候启动会出错

**Comment by heavyrain2012** [comment]
可以复用 wildfirechat.sh wildfirechat.conf c3p0.xml 这3个问题， hazelcast.xml需要对比一下有没有变化，没有变化也可以用旧的，其他用新的
