### ISSUE TITLE
撤回消息

### ISSUE THREAD

**Issue by doralines** [wildfirechat/wfc_flutter_plugins#89]
现在我们测试的时候 RecallNotificationContent 会重复推送，RecallMessageEvent 推送了一次，我们更新了那一条消息，然后ReceiveMessagesEvent 也推送了一次，我认为ReceiveMessagesEvent这里应该不推送撤回消息得呀。不然就重复渲染了

**Comment by heavyrain2012** [comment]
当收到消息时需要过滤一下，如果有重复消息就更新一下，不再插入新消息这样就不会有问题了。
