### ISSUE TITLE
有些消息，中文乱码

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/wfc_flutter_plugins#9]
比如在修改群名称的通知消息下，获取的name是乱码

改成utf8.decode就不乱码了。。。
`  @override
  void decode(MessagePayload payload) {
    super.decode(payload);
    Map<dynamic, dynamic> map =
        json.decode(utf8.decode(payload.binaryContent));
    operateUser = map['o'];
    groupId = map['g'];
    name = map['n'];
  }`

话说flutter的sdk的bug是真的多啊

**Comment by heavyrain2012** [comment]
已经替换处理。非常感谢您的提醒！我们没有flutter工程师也没有做过flutter的项目，所以写个这个插件时只能简单地做个语言转换，把android或者iOS的功能接口转化为flutter接口，如果还有其它用的不对的地方，还请多多指正。
