### ISSUE TITLE
为什么某些消息类型的一些字段会莫名消失掉

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#91]
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/ec78e67e-8c3f-4fd7-b005-31baffa7e4e5)
例如这个link类型
late String title;
late String contentDigest;
late String url;
String? thumbnailUrl;
4个字符串类型我都给了，并且成功发送了消息，可是后面成功得到的只有title，其他3个都是空或者空字符串

**Comment by li460930736** [comment]
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/0d6f3b83-1615-4c31-b542-8e81b819eb79)
可以看到，发送消息的时候这几个都带了字符串

**Comment by heavyrain2012** [comment]
你打印一下发送encode的messagePayload和后面从协议栈读取出来的messagePayload是不是一致的，一般这个不会有问题的

**Comment by heavyrain2012** [comment]
4个字符串类型我都给了，并且成功发送了消息，可是后面成功得到的只有title，其他3个都是空或者空字符串

后面成功得到的  检查一下是从哪里得到的，是上层组合成的还是从协议栈读取的？

**Comment by li460930736** [comment]
> messagePayload
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/e0092872-f577-402d-aa3f-1f18dc3d7fb2)


![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/9ff26157-7436-4997-b2cd-495e1fea7447)
是在这里打印吗？invokeMethod以后从Unit8List变了，变成一个"e30="

**Comment by heavyrain2012** [comment]
我们用flutter版本和原生版本互发这个消息，发现有个空异常的问题，解决完之后，互发这个消息就没有问题了。请用master最新版本验证一下，如果还有问题，请加微信 wildfirechat
