### ISSUE TITLE
一些关于接口的建议

### ISSUE THREAD

**Issue by doralines** [wildfirechat/wfc_flutter_plugins#93]
1.给一个异步的可以获取单个群成员信息的接口，在一些场景下会方便一点
2.根据角色获取群成员列表 如果本地没有对应的数据 是不会触发GroupMemberUpdate那个回调的，这样返回的列表始终都是空的

**Comment by heavyrain2012** [comment]
1. 这个问题我们仔细考虑了一下，目前协议栈的同步机制没有办法做到单独同步一个成员的办法，还是只能用原来的办法。
2. 今天更新的版本已经加上这个功能了
