### ISSUE TITLE
getUserInfoAsync 的问题

### ISSUE THREAD

**Issue by doralines** [wildfirechat/wfc_flutter_plugins#95]
getUserInfoAsync这个接口的原理是 如果本地没有，就从远端拉取吗？这个接口获取的用户是没有friendAlias的，必现

**Comment by heavyrain2012** [comment]
协议栈的问题，已经解决和提交了，请更新验证。注意最近分支有变动，原来的master改成 native-rtc-ui分支了，请同步这个分支上的更新

**Comment by doralines** [comment]
那这个接口原理是不是  如果本地没有，就从远端拉取。优先级还是先获取本地的

**Comment by heavyrain2012** [comment]
对的，如果本地有就直接callback回去。如果本地没有就从服务器拉取，拉取成功后再callback回去
