### ISSUE TITLE
如何在群内@某人或者所有人

### ISSUE THREAD

**Issue by li460930736** [wildfirechat/wfc_flutter_plugins#96]
![image](https://github.com/wildfirechat/wfc_flutter_plugins/assets/56672001/425d2b46-462c-4402-8a6e-7b71a749b861)
我根据这个messageContent，设置mentionedType为1，再mentionedTargets内添加对应用户的userId，貌似跟普通消息没区别，debug出来的消息也是普通的消息，该功能是否还未实现？

**Comment by heavyrain2012** [comment]
收到的消息只有消息状态能区分，普通消息收到后是unread，@消息收到后是mentioned，请清除未读之后都变成readed

**Comment by li460930736** [comment]
> 收到的消息只有消息状态能区分，普通消息收到后是unread，@消息收到后是mentioned，请清除未读之后都变成readed

谢谢回复，请问如何能发出mentioned类型的消息？我改变mentionedType，可是接收方收到的也是unread

**Comment by heavyrain2012** [comment]
> > 收到的消息只有消息状态能区分，普通消息收到后是unread，@消息收到后是mentioned，请清除未读之后都变成readed
> 
> 谢谢回复，请问如何能发出mentioned类型的消息？我改变mentionedType，可是接收方收到的也是unread

加微信 wildfirechat 我们问一下情况

**Comment by li460930736** [comment]
更新了aar文件和message.dart文件以后可以了

**Comment by heavyrain2012** [comment]
好的
