### ISSUE TITLE
视频/语音通话问题

### ISSUE THREAD

**Issue by moQingTing** [wildfirechat/wfc_flutter_plugins#98]
我使用了分支native-rtc-ui 的最新版本
场景：当前用户在通话中并且缩小窗口，然后再发起另外一个好友的视频或语音通话，就会显示一个空白的加载中页面（预期结果应该是无法进行通话）
平台：安卓端
<img width="882" alt="image" src="https://github.com/wildfirechat/wfc_flutter_plugins/assets/18046454/670cb322-d6c9-4b2a-a6f3-e50aace1d519">

**Comment by heavyrain2012** [comment]
这是我们测试用的turn服务因为压力太大出了问题，重启以后就好了。如果你们应用上线了，请部署你们自己的turn服务，避免我们测试用的turn服务出问题

**Comment by heavyrain2012** [comment]
最新版本已经解决，请更新后验证

**Comment by heavyrain2012** [comment]
感觉这个界面像是master分支的，请确认用的是那个分支还有最新版本还有问题吗
